### PR TITLE
Install headers and C++ library, put replayer and client into a single module

### PR DESCRIPTION
**Pull request by jgehring**
This re-organizes the build system and source layout so that we can install a
pure-C++ TorchCraft library with luarocks. I decided to stick to the Lua
eco-system for now to keep things simple; if needed, we could still add support
for a "standard" libtorchcraft installation later.

The source code is now organized as follows:
 - include/ contains header files that will be installed and are usable with
   non-Lua clients (i.e. using libtorchcraft only). This should probably also
   include others like gamestore.h, but there are some Lua dependencies left to
   be factored out.
 - replayer/ and client/ contain source files and internal headers for
   libtorchcraft.
 - lua/ contains Lua wrappers for code in replayer/ and client/.

There is now a single C++ Lua module containing both client and replayer
functionality, dubbed 'tc_lib'. For convenience and compatibility, replayrer.lua
and client.lua are provided which simply return the appropriate table from the
C++ module.

### CODE REVIEW

**Comment by jgehring** [comment]
Please let me know what you guys think of the re-organization. Unification of namespaces (`torchcraft` instead of `replayer` and `client`) will follow afterwards. I'm not sure whether Lua code should still pretend there's a separate `replayer` and `client` module.

**Comment by edran** [comment]
LGTM :tada:

**Comment by jgehring** [comment]
@edran are you referring to the C++ code or the Lua modules? I could rename `client` to `torchcraft` and `replayer` to `torchcraft::replayer` on the C++ side and have the Lua C++ module simply return a table that contains everything in `torchcraft.client` as well as definitions in `replayer` as a sub-table. `init.lua` could then pull the definitions from that table into the top-level `torchcraft` namespace. In other words, promote `client` to the top level and keep the `replayer` sub-namespaces in both C++ and Lua.

**Comment by edran** [comment]
@jgehring Yes, that's roughly what I mean. Alternatively the root level `torchcraft` could be empty (say, similarly to Penlight) and we'd have `torchcraft.client`, `torchcraft.replayer`, etc. for all the interfaces

I think that's the convention in Python, but I can't think of any significant downside either way in this case.

**Comment by jgehring** [comment]
AFAIK this varies from project to project, but here an empty `torchcraft` top-level namespace will require quite some refactoring in init.lua and existing code. Also, in some sense the Lua `torchcraft` module is the code required to connect to the server so `torchcraft.client` feels a little redundant. Let's go with `torchcraft` and `torchcraft.replayer`.

**Pull request merged**
