### PR TITLE
Fix reconnecting with client/openbw

### PR DESCRIPTION
**Pull request by tscmoo**
by correctly sending the handshake on reconnect if we are in a game

### CODE REVIEW

**Comment by syhw** [comment]
For the functionality of this patch. It now looks redundant in the or.

**Comment by jgehring** [comment]
I see. @tscmoo can you remove the check for is_client then?

**Comment by tscmoo** [comment]
Sorry, didn't notice this comment.
Hmm, I'm not sure if the is_client check can be removed. BWAPI::Broodwar shouldn't be used unless the client is connected, and BWAPI::BWAPIClient should only be used if controller->is_client.
The parenthesis could be around the || instead of the && though, behavior would be the same. *shrug*

**Comment by jgehring** [comment]
@tscmoo is right, the is_client is still needed. It's a bit confusing since `handleReconnect` is also called for the initial handshake. In client mode, the server handshake is sent from `initGame` instead, i.e. after connecting to StarCraft.

**Pull request merged**
