### PR TITLE
Don't transpose map data, fix tensor representation

### PR DESCRIPTION
**Pull request by jgehring**
@edran, I assume this will affect the drawing commands in init.lua?

### CODE REVIEW

**Comment by edran** [comment]
I believe it should be fine. In any case I'm going to move most of the drawing functions into the C++ layer under another namespace before then next release, so it's relatively safe to break this in `develop`.

**Comment by ebetica** [comment]
This will affect new dumped replays as well, yes?

**Comment by jgehring** [comment]
Map data is not stored in frames, so as long as you are saving Frame objects only you should be fine.

**Comment by ebetica** [comment]
But they are stored in the replays, no? https://github.com/TorchCraft/TorchCraft/blob/master/include/replayer.h#L42

It's an easy change though, I just want to know whether I need to do it :)

**Comment by jgehring** [comment]
Yeah, I think you're right. Note that previously, the data was transposed but also had the wrong size (width instead of height and vice versa), i.e. for non-square maps some portions are omitted while others are not actually there and presumably simply marked with -1.

**Pull request merged**
